name: very_good_coffee
description: "Very Good Coffee - Save your favorite coffee pictures"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  
  # Navigation
  go_router: ^14.6.1
  
  # Dependency Injection
  get_it: ^8.0.2
  
  # Networking
  dio: ^5.7.0
  
  # Logging
  talker_flutter: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_bloc_logger: ^4.4.1
  
  # Internationalization
  slang: ^3.31.2
  slang_flutter: ^3.31.0
  
  # Local Storage
  path_provider: ^2.1.4
  
  # UI
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  very_good_analysis: ^9.0.0
  
  # Testing
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  
  # Code Generation
  slang_build_runner: ^3.31.0
  build_runner: ^2.4.13

flutter:
  generate: true
  uses-material-design: true
